apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-cicd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-cicd-app
  template:
    metadata:
      labels:
        app: cloud-cicd-app
    spec:
      containers:
        - name: cloud-cicd-app
          image: 122066462721.dkr.ecr.ap-south-1.amazonaws.com/cloud-cicd-app:latest
          ports:
            - containerPort: 5000