name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: python -m pytest

      - name: Security scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Build Docker image
        run: docker build -t cloud-cicd-app .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::122066462721:role/GitHubActionsEKSRole
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker image
        run: |
          docker tag cloud-cicd-app:latest 122066462721.dkr.ecr.ap-south-1.amazonaws.com/cloud-cicd-app:${{ github.sha }}
          docker tag cloud-cicd-app:latest 122066462721.dkr.ecr.ap-south-1.amazonaws.com/cloud-cicd-app:latest

      - name: Push Docker image to ECR
        run: |
          docker push 122066462721.dkr.ecr.ap-south-1.amazonaws.com/cloud-cicd-app:${{ github.sha }}
          docker push 122066462721.dkr.ecr.ap-south-1.amazonaws.com/cloud-cicd-app:latest

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ap-south-1 --name cloud-cicd-cluster

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/cloud-cicd-app cloud-cicd-app=122066462721.dkr.ecr.ap-south-1.amazonaws.com/cloud-cicd-app:${{ github.sha }}
          kubectl rollout status deployment/cloud-cicd-app